[mypy]
python_version = 3.13
ignore_missing_imports = True
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True
follow_imports = normal
strict_equality = True
explicit_package_bases = True

[mypy-src.weatherender.API.*]
ignore_errors = True

[mypy-src.weatherender.WEB.*]
ignore_errors = True

[mypy-src.weatherender.CLI.*]
ignore_errors = True

[mypy-src.weatherender.logging_config]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True
